### ISSUE TITLE
Send welcome emails

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/pmpro-add-member-admin#15]
somehow implement:

1. they get some kind of welcome e-mail, maybe with the user-notes or an extra field

1. they get an e-mail where they can send the password (didn’t work at all on my side)

**Comment by dparker1005** [comment]
> 1. they get some kind of welcome e-mail, maybe with the user-notes or an extra field
Tracking this kind of behavior in #6 

> 2. they get an e-mail where they can send the password (didn’t work at all on my side)
This behavior appears to be working as expected in the most recent version of this Add On. If this is still an issue that you are seeing, please leave a comment on this GitHub Issue so that we can look further into this.
