### ISSUE TITLE
Force non-required fields to be required

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-add-member-admin#17]
A user has requested that first name and last name fields are required.

Maybe we can add in a filter to make this easier, a filter for field attributes?

**Comment by dparker1005** [comment]
The `pmpro_add_member_required_user_fields` filter can be used to do this: https://github.com/strangerstudios/pmpro-add-member-admin/blob/1cd50233cf8dccb88201214fdf992646028ad284/adminpages/addmember.php#L123-L128
