### ISSUE TITLE
Change Joined date

### ISSUE THREAD

**Issue by myrafletcher** [strangerstudios/pmpro-add-member-admin#18]
I need the admin to be able to edit the joined date not just expiry date how can I do this?

**Comment by dparker1005** [comment]
This is possible with custom development. You can use the `pmpro_add_member_fields` hook to add the field to the "Add Member" page and then the `pmpro_add_member_added` hook to update the user's joined date based on the field's content when the "Add Member" page is submitted.

Here is an example of those hooks being used to set a user's bbPress role on the "Add Member" page: https://gist.github.com/pbrocks/bae0b08b11d5832884900e5b83e505bd

If you have further questions about how to add that functionality to your site, please <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.

**Comment by BlueApple865729** [comment]
wonderful!

**Comment by shiningapostar** [comment]
> wonderful!

hi, how did you do it?
