### ISSUE TITLE
Bug: "+order" screen displays Add Member for document title.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-add-member-admin#21]
The "+order" screen displays Add Member for the document title in the browser. This may be confusing for users.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/wrong-title-in-browser-tab-for-add-order/

**Comment by dparker1005** [comment]
This issue was addressed in a commit here: https://github.com/strangerstudios/pmpro-add-member-admin/commit/df3c507f053cd65018a9be7dba4f833283a20ff9
