### ISSUE TITLE
PHP Warning:  array_merge()

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-add-member-admin#24]
PHP Warning:  array_merge(): Argument #1 is not an array in /pmpro-add-member-admin/pmpro-add-member-admin.php on line 120

**Comment by dparker1005** [comment]
Currently line 132: https://github.com/strangerstudios/pmpro-add-member-admin/blob/1cd50233cf8dccb88201214fdf992646028ad284/pmpro-add-member-admin.php#L132

**Comment by michaelbeil** [comment]
Bumping this [PR](https://github.com/strangerstudios/pmpro-add-member-admin/pull/37) as it's still an issue (ticket ID 408360 mods only).
