### ISSUE TITLE
BUG: Register Helper Add On – fields also appear on Add Order page

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-add-member-admin#25]
The Register Helper fields show on the Add Order page
https://www.paidmembershipspro.com/forums/topic/bug-register-helper-add-on-fields-also-appear-on-add-order-page/

**Comment by dparker1005** [comment]
Linking this to #36 . If we decide to have the `+order` link go to the default PMPro "New Order" page, then this should no longer be an issue.

**Comment by andrewlimaza** [comment]
For now, please set `"addmember" => true/flase` if you want to show or hide it. Default is false, it makes sense that sometimes people would want to capture the member information while adding the member and creating the order.
