### ISSUE TITLE
User Notes not seen in order details.

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-add-member-admin#26]
Order Notes are viewable in the Order details, great, but User Notes are nowhere to be seen.

https://www.paidmembershipspro.com/forums/topic/feature-request-add-member-from-admin-add-on-user-notes/

**Comment by tictag** [comment]
@femiyb  Only PMPro admins will be able to see that page, for everybody else, here's some extra information:

Currently the Add Member From Admin Add On captures both User Notes and Order Notes and stores them in user and order meta as user_notes and order_notes, respectively.

Order Notes are viewable in the Order details, great, but User Notes are nowhere to be seen.

Yes, you can install the Register Helper Add On and using some code have these notes appear in the User Profile per advice from Jason Coleman here: https://www.paidmembershipspro.com/adding-new-members-or-updating-existing-members-as-administrator-or-membership-manager-role/#comment-34102

**…but really?** I have to install a completely different plugin (two plugins when you also consider the pmpro_customizations.php plugin) and write some code to see these User Notes?

As a feature request, I think adding a self-contained method of viewing these User Notes would not only be useful to your customers but also kinda expected, I mean, what’s the point of capturing these notes if you can’t see them anywhere?

Maybe you could add a checkbox to the ‘Add Member’ page, something like:

- “Add these notes to the User Profile? (Y/n)”
- “Add these notes to the Members List CSV extract (Y/n)?”

Hope this helps,
Regards,
David.

**Comment by ipokkel** [comment]
To currently display "User Notes" on the user's profile page in the WordPress Dashboard and include the notes in the members list CSV export the following code snippet, depending on the Register Helper add on installed and activated, may be added to a customization plugin.

https://gist.github.com/ipokkel/21a75166b53910548ff9f920025043f9
