### ISSUE TITLE
Change text that says " Send this password to the new user by email."

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-add-member-admin#27]
`When i add a new member from the add member add-on, it gave me an option to send a password via email. Actually that is is not to send a password but rather to set a password.`

Change the text to "Send the new user an email about their account."

**Comment by andrewlimaza** [comment]
I think the email logic needs to be reworked slightly.

**Comment by andrewlimaza** [comment]
Fixed in latest commit. Wording has changed, logic hasn't changed.
