### ISSUE TITLE
adminpages/addmember.php - File has mixed line endings

### ISSUE THREAD

**Issue by leesonthenet** [strangerstudios/pmpro-add-member-admin#30]
FILE: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/pmpro-add-member-admin/adminpages/addmember.php
-----------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------
 1 | WARNING | File has mixed line endings; this may cause incorrect results
-----------------------------------------------------------------------------------------------------------

**Comment by leesonthenet** [comment]
Line 295 has an unnecessary <CR> in addition to the <LF> - throws a PHP Warning in Wordpress PHP Compatibility Checker.  Easy fix. :)

**Comment by dparker1005** [comment]
I just tried running the [WP Engine Compatibility Checker plugin](https://en-au.wordpress.org/plugins/php-compatibility-checker/) on a site running this add on, and wasn't able to get this warning to show while testing for `7.0` compatibility or `7.3` compatibility, so it appears that this issue has been fixed. If you can still get this warning to show, please let us know and we can re-open this issue.
