### ISSUE TITLE
Not compatible with PMP Register Helper v1.3

### ISSUE THREAD

**Issue by markkelly1982** [strangerstudios/pmpro-add-member-admin#4]
Hi Jason,

Saving fields is not working from the 'Add Member' screen when V1.3 of Register Helper is installed. V1.2 works. 

The page adds the member but doesn't save any of the custom fields. 

In WordPress debug mode, it brings 

`Notice: Trying to get property of non-object in ../wp-content/plugins/pmpro-register-helper/pmpro-register-helper.php on line 725`

`Notice: Trying to get property of non-object in ../wp-content/plugins/pmpro-register-helper/pmpro-register-helper.php on line 745`

although these errors are present in v1.2 however it still works.

**Comment by eighty20results** [comment]
There's a pull request against Register Helper to mitigate this issue. Jason is aware & may incorporate the pull-request, based on available testing resources, plus whatever the next release vehicle is and whether the testing requirements can be met.

**Comment by dparker1005** [comment]
I am closing this issue as this appears to have been addressed in the PR in the Register Helper repository: https://github.com/strangerstudios/pmpro-register-helper/pull/77. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
