### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT - Unable to find End of Central Dir Record signature

### ISSUE THREAD

**Issue by gravitytechau** [strangerstudios/pmpro-add-member-admin#43]
Hi,

There's a website that I do maintenance on and it's been getting the following error on while trying to update the pmpro-add-member-admin v0.7.2 (& pmpro-multiple-memberships-per-user v0.6.3, & pmpro-shipping v0.8) for months, possibly years.

`Update failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`

I had assumed that it was new when I started to look after the site and would be resolved over time, but it doesn't seem to resolve itself. 

Can you please point me in the right direction?

**Comment by andrewlimaza** [comment]
Sorry for only replying now we don't monitor our Github repositories for support requests.This sounds like there could be an issue with your license key. If you are still having issues, please can you open a ticket on www.paidmembershipspro.com/support for further assistance.

You may manually update your plugin by downloading and uploading it via FTP to overwrite it.
