### ISSUE TITLE
BUG: Add Member email sent to admin is using the admin details

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-add-member-admin#47]
**Describe the bug**
As reported in ticket 415715 (moderators only), admin details are used instead of member details. admin name

**To Reproduce**
1. Add a member.
2. Admin details are used instead of member details.

**Screenshot**
![image](https://user-images.githubusercontent.com/4752949/163233857-766d0557-1643-4095-a079-eb6681c8230e.png) 

**Expected behavior**
The email should include member details.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro and  is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.7.5, Add Member From Admin 0.7, Twenty Twenty-One 1.4, WordPress 5.9.3, and PHP 7.4.1.
```
</details>

**Comment by andrewlimaza** [comment]
Unable to replicate this, these are the steps that I followed:

* Navigated to Memberships > Add Member.
* Fill out new information for the user (I named them explicitly not admin for tests)
* Check MailHog to see email, screenshot attached that's sent to the user.


![Screen Shot 2022-04-14 at 13 23 20](https://user-images.githubusercontent.com/12629136/163381499-499e7bca-bb8c-4d1b-87f0-91e12ffcfdbf.png)

**Comment by andrewlimaza** [comment]
This has been fixed in latest dev branch, point release should go out soon.
