### ISSUE TITLE
Version 0.7 not display member information.

### ISSUE THREAD

**Issue by delgensocorg** [strangerstudios/pmpro-add-member-admin#48]
After installing Version 0.7 pmpro-ad-member-admin we were unable to view member information after clicking the +Order button.  I should also say that we do have custom fields in the [PMPro Register Helper Custom Fields] snippet.  When clicking the +Order button, with version 0.7 installed we see the default Add Order and no member data.

To Resolve:

1. Deactivated and deleted version 0.7
2. Downloaded and installed/activated version 0.6.
3. All back to normal and the +Order displays member ID and detail again.

The attached file has v.07 and v.06 examples.
[pmpro-Member-Order-add-v.07.pdf](https://github.com/strangerstudios/pmpro-add-member-admin/files/8484440/pmpro-Member-Order-add-v.07.pdf)

Graham

**Comment by andrewlimaza** [comment]
Thanks for bringing this to our attention Graham, we have reverted functionality that will go out in V0.7.1 - https://github.com/strangerstudios/pmpro-add-member-admin/commit/fc21e975b84add8c8b7ee50a5eb198c71da76f7c
