### ISSUE TITLE
Send 'admin_change' email when user is added.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-add-member-admin#6]
No emails are sent out to the user from PMPro when a user is added to a level.

We should send an email when a user is added with a membership level.

**Comment by andrewlimaza** [comment]
Gist example - https://gist.github.com/andrewlimaza/372d1d08c75c64f7bb757d72f5932907

**Comment by mhartste** [comment]
Do you also have some comparable code to send the Invoice email to the member when an order is manually entered?  

When the member enters a membership transaction by check, they receive an immediate confirmation email with check mailing instructions.  Then, when we receive the check and change the order from pending to success they receive an Invoice email as a receipt of their transaction.  This Invoice email should also be sent to the member if our admin manually enters an order.

Thanks,

Mike

**Comment by dparker1005** [comment]
> Do you also have some comparable code to send the Invoice email to the member when an order is manually entered?
> 
> When the member enters a membership transaction by check, they receive an immediate confirmation email with check mailing instructions. Then, when we receive the check and change the order from pending to success they receive an Invoice email as a receipt of their transaction. This Invoice email should also be sent to the member if our admin manually enters an order.
> 
> Thanks,
> 
> Mike

Gist for this can be found here - https://gist.github.com/dparker1005/59f6a854e980d5595e1a4280f154cfad

**Comment by dparker1005** [comment]
#31 proposes adding a new email template, which should fill the same gap as this proposal.
